#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const packageConfig = Object.assign({}, require('../package.json')) // copy
const outputPath = path.join(__dirname, '../dist/package.json')

delete packageConfig.private
delete packageConfig.devDependencies
delete packageConfig.scripts

packageConfig.main = 'main.umd.js'
packageConfig.module = 'main.esm.js'

fs.writeFileSync(outputPath, JSON.stringify(packageConfig, null, '  '))
