#!/usr/bin/env bash

set -e # always immediately exit upon error

scripts_dir=`dirname $0`

"$scripts_dir/require-clean-working-tree"

publish_args='--access public'
version_tag=`git tag -l --points-at`

if [[ ! "$version_tag" ]]
then
    echo "A new version must be built first"
    exit 1
fi

if [[ "$1" == '--production' ]]
then
    shift # remove this the first arg
    git push
    git push origin "$version_tag"
    echo 'Will push to REAL NPM registry'
else
    publish_args="$publish_args --registry http://localhost:4873"
    echo 'Will push to test NPM registry'
fi

cd dist
npm publish $publish_args "$@"
