#!/usr/bin/env bash

# remaining args go to npm-publish

set -e # always immediately exit upon error

scripts_dir=`dirname $0`
current_branch=`git symbolic-ref --quiet --short HEAD`
version_num=$1
production_arg=$2
publish_args='--access public'

if [[ ! "$version_num" ]]
then
    echo 'Must specify an exact version number'
    exit 1
fi

shift # remove version arg

if [[ "$production_arg" == '--production' ]]
then
    shift # remove production arg
    echo 'Publishing to PRODUCTION'
else
    echo 'Publishing as a TEST'
    publish_args="$publish_args --registry http://localhost:4873"
fi

"$scripts_dir/require-clean-working-tree"

version_tag="v$version_num"

echo 'Checking out dist files'

rm -rf dist
git checkout "$version_tag" -- dist
git reset

cd dist
echo 'TEST!!!' npm publish $publish_args "$@"

if [[ "$production_arg" == '--production' ]]
then
    echo 'TEST!!!' git push
    echo 'TEST!!!' git push origin "$version_tag"
fi
