#!/usr/bin/env bash

set -e # always immediately exit upon error

scripts_dir=`dirname $0`

"$scripts_dir/require-clean-working-tree"

publish_args='--access public'
version_tag=`git tag -l --points-at`

if [[ ! "$version_tag" ]]
then
    echo "A new version must be built first"
    exit 1
fi

if [[ "$1" == '--production' ]]
then
    shift # remove this the first arg
    is_production=1
    echo 'Publishing to PRODUCTION'
else
    is_production=0
    echo 'Publishing as a TEST'
fi

if [[ "$is_production" == '0' ]]
then
    publish_args="$publish_args --registry http://localhost:4873"
fi

cd dist
npm publish $publish_args "$@"

if [[ "$is_production" == '1' ]]
then
    git push
    git push origin "$version_tag"
fi
