#!/usr/bin/env bash

# remaining args go to npm-version

# always immediately exit upon error
set -e

scripts_dir=`dirname $0`

if [[ ! "$@" ]]
then
    echo 'You must supply a version argument'
    exit 1
fi

"$scripts_dir/require-clean-working-tree"
"$scripts_dir/update-deps" || npm install # always. needed?

current_commit=`git rev-parse HEAD`
current_branch=`git symbolic-ref --quiet --short HEAD`

git checkout --detach

if npm version "$@"
then
    echo 'Successfully built new version release'
else
    git reset --hard "$current_commit"
fi

git checkout "$current_branch"
