#!/usr/bin/env bash

# remaining args go to npm-version

# always immediately exit upon error
set -e

scripts_dir=`dirname $0`

if [[ ! "$@" ]]
then
    echo 'You must supply a version argument'
    exit 1
fi

"$scripts_dir/require-clean-working-tree"
"$scripts_dir/update-deps"

current_ref=`git symbolic-ref --quiet HEAD`
git checkout --detach

if npm version "$@"
then
    echo 'Successfully built new version release'
fi

git symbolic-ref HEAD "$current_ref"
git reset
